### ISSUE TITLE
Fails with Rspec 2 and 3

### ISSUE THREAD

**Issue by kristianmandrup** [fakefs/fakefs#215]
Gemfile

``` ruby
group :test do
  gem "rspec",    "3.0.0.beta2"
  gem "fakefs"
end
```

``` ruby
require 'rspec'
require 'fakefs'

describe 'x' do
end
```

```
C:\dev-projects\MC-prepare\mc-file-prepare>rspec spec/mc-file-prepare/test_spec.rb
C:/Ruby200-x64/lib/ruby/2.0.0/pp.rb:391:in `<top (required)>': superclass mismatch for class File (TypeError)
        from C:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from C:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-expectations-3.0.0.beta2/lib/rspec/expectations/diff_presenter.rb:5:in `<top
 (required)>'
        from C:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from C:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-expectations-3.0.0.beta2/lib/rspec/expectations.rb:10:in `<top (required)>'
        from C:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from C:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0.beta2/lib/rspec/core/configuration.rb:484:in `block in expect_wit
h'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0.beta2/lib/rspec/core/configuration.rb:479:in `map'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0.beta2/lib/rspec/core/configuration.rb:479:in `expect_with'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0.beta2/lib/rspec/core/configuration.rb:447:in `expectation_framewo
rks'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0.beta2/lib/rspec/core/configuration.rb:925:in `configure_expectati
on_framework'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0.beta2/lib/rspec/core/example_group.rb:358:in `ensure_example_grou
ps_are_configured'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0.beta2/lib/rspec/core/example_group.rb:372:in `set_it_up'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0.beta2/lib/rspec/core/example_group.rb:321:in `subclass'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0.beta2/lib/rspec/core/example_group.rb:287:in `example_group'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0.beta2/lib/rspec/core/example_group.rb:169:in `block in alias_exam
ple_group_to'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0.beta2/lib/rspec/core/dsl.rb:40:in `block in expose_example_group_
alias'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0.beta2/lib/rspec/core/dsl.rb:74:in `block (2 levels) in expose_exa
mple_group_alias_globally'
        from C:/dev-projects/MC-prepare/mc-file-prepare/spec/mc-file-prepare/test_spec.rb:4:in `<top (required)>'
```

Switching to rspec 2.14.7

```
C:\dev-projects\MC-prepare\mc-file-prepare>bundle exec rspec spec/mc-file-prepare/test_spec.rb
DL is deprecated, please use Fiddle
C:/Ruby200-x64/lib/ruby/2.0.0/pp.rb:391:in `<top (required)>': superclass mismatch for class File (TypeError)
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-expectations-2.14.5/lib/rspec/expectations/differ.rb:3:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-expectations-2.14.5/lib/rspec/expectations/differ.rb:3:in `<top (required)>'

        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-expectations-2.14.5/lib/rspec/expectations.rb:10:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-expectations-2.14.5/lib/rspec/expectations.rb:10:in `<top (required)>'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:447:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:447:in `block in expect_with'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:442:in `map'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:442:in `expect_with'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:410:in `expectation_frameworks'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:889:in `configure_expectation_fr
amework'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:281:in `ensure_example_groups_ar
e_configured'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:295:in `set_it_up'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:245:in `subclass'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:232:in `describe'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/dsl.rb:18:in `describe'
        from C:/dev-projects/MC-prepare/mc-file-prepare/spec/mc-file-prepare/test_spec.rb:4:in `<top (required)>'
```

I wonder if it is a Ruby 2.0 issue?

**Comment by AlphaHydrae** [comment]
Hi, I'm having the same error with Ruby 2.2.1 and RSpec 3.3.0:

     TypeError:
       superclass mismatch for class File
     # /Users/ah/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/pp.rb:419:in `<top (required)>'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-support-3.3.0/lib/rspec/support/differ.rb:5:in `require'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-support-3.3.0/lib/rspec/support/differ.rb:5:in `<top (required)>'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-expectations-3.3.1/lib/rspec/expectations/fail_with.rb:6:in `differ'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-expectations-3.3.1/lib/rspec/expectations/fail_with.rb:25:in `fail_with'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:38:in `handle_failure'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-expectations-3.3.1/lib/rspec/expectations/expectation_target.rb:54:in `to'
     # ./spec/config_spec.rb:339:in `block (5 levels) in <top (required)>'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:206:in `instance_exec'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:206:in `block in run'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430:in `block in with_around_and_singleton_context_hooks'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388:in `block in with_around_example_hooks'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478:in `block in run'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:616:in `run_around_example_hooks_for'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478:in `run'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388:in `with_around_example_hooks'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430:in `with_around_and_singleton_context_hooks'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:203:in `run'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:559:in `block in run_examples'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:555:in `map'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:555:in `run_examples'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:521:in `run'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `block in run'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `map'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `run'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `block in run'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `map'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `run'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `block in run'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `map'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `run'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `map'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1627:in `with_suite_hooks'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:114:in `block in run_specs'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:77:in `report'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:113:in `run_specs'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:89:in `run'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
     # /Users/ah/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'
     # /Users/ah/.rvm/gems/ruby-2.2.1/bin/rspec:23:in `load'
     # /Users/ah/.rvm/gems/ruby-2.2.1/bin/rspec:23:in `<main>'
     # /Users/ah/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
     # /Users/ah/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

I assume that the error is caused by the incompatibility between these two lines in FakeFS and in Ruby's pretty print class:

* https://github.com/defunkt/fakefs/blob/v0.6.7/lib/fakefs/file.rb#L5
* https://github.com/ruby/ruby/blob/v2_2_1/lib/pp.rb#L419

The solution described above did not work for me. Did anyone find another workaround?

**Comment by tovodeverett** [comment]
The solution in https://github.com/defunkt/fakefs/issues/99 worked for me, namely adding `require 'pp'`.

**Comment by rockylaw** [comment]
@AlphaHydrae i met the same issue.

**Comment by EdDeAlmeidaJr** [comment]
I'm using Rails 2.4.6 with Ruby 2.3.1 and RSpec 3.5.2. I'm getting the same error when doing this test

  	it 'returns true if the component\'s base directory is missing' do
          FakeFS do
            FileUtils.mkdir('./web') if not Dir.exist?('./web')
            expect(Dir.entries('./web').include?('assets')).to be true
            expect(Dir.entries('./web/assets').include?('components')).to be true
          end
        end

As you may see, a simple test to check directory structure.

**Comment by grosser** [comment]
the issues seems to be that FakeFS got included into the global namespace ?
any idea where this happens / how to avoid ?

**Comment by grosser** [comment]
... yeah FakeFs removes File etc constants and replaces them ... only real solution would be to make FakeFs `File` inherit from IO ... which would be tricky ...

global const messing is just not fun ... loading pp earlier makes the Faile::Stat patches pp adds ... but I guess that's not a big issue ...

**Comment by ianfixes** [comment]
Google brought me here to find a fix.  And none of these fixes worked. Then Google brought me to the [fix I had already submitted for this project](https://github.com/fakefs/fakefs/pull/366) that fixes this exact thing. 🤦‍♂️ 

To "future me, who will inevitably make this mistake again": adding `require 'pp'` to your Gemfile will fix this.  Yes, even for gems:

```ruby
source "https://rubygems.org"
require 'pp'
gemspec
```
