### ISSUE TITLE
undefined method `foreach' for FakeFS::File:Class (NoMethodError)

### ISSUE THREAD

**Issue by sshaw** [fakefs/fakefs#263]
```
~ >gem list fakefs

*** LOCAL GEMS ***

fakefs (0.6.0)
~ >ruby -rfakefs/safe -e'FakeFS { File.write("A","123"); p File.foreach("A").to_a }'
-e:1:in `block in <main>': undefined method `foreach' for FakeFS::File:Class (NoMethodError)
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/fakefs-0.6.0/lib/fakefs/base.rb:70:in `with'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/fakefs-0.6.0/lib/fakefs/base.rb:94:in `FakeFS'
	from -e:1:in `<main>'
```

**Comment by misaka** [comment]
I've created a [PR for this](https://github.com/defunkt/fakefs/pull/294).
