### ISSUE TITLE
Merge pull request #226 from dekz/kernel_hijack brings some errors that still lasts

### ISSUE THREAD

**Issue by scythargon** [fakefs/fakefs#266]
Greetings from jetradar.com dev team and thank you for your awesome gem!

Recently we noticed that some of our specs fail if run not in parallel mode. I've made some research and sort of localized the problem - it appears in verions 0.5.3 in this merge commit: `76483b56086eb9df74d584425838e2a760a7afc7 : Merge pull request #226 from dekz/kernel_hijack`
and lasts till the very new version (v0.6.0 at the moment of writing)
Our error e.g.:

```
  1) Money::Bank::XeExchange#request_rate with real request returns rates given right currencies
     Failure/Error: subject.request_rate('USD', 'EUR').should be > 0
     ArgumentError:
       wrong number of arguments (0 for 1)
     # /home/argon/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/open-uri.rb:27:in `open'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/bundler/gems/fakefs-76483b56086e/lib/fakefs/kernel.rb:18:in `call'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/bundler/gems/fakefs-76483b56086e/lib/fakefs/kernel.rb:18:in `block (2 levels) in unhijack!'
     # /home/argon/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/open-uri.rb:29:in `open'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/bundler/gems/fakefs-76483b56086e/lib/fakefs/kernel.rb:18:in `call'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/bundler/gems/fakefs-76483b56086e/lib/fakefs/kernel.rb:18:in `block (2 levels) in unhijack!'
     # /home/argon/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/open-uri.rb:29:in `open'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/bundler/gems/fakefs-76483b56086e/lib/fakefs/kernel.rb:18:in `call'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/bundler/gems/fakefs-76483b56086e/lib/fakefs/kernel.rb:18:in `block (2 levels) in unhijack!'
     # ./lib/money/bank/xe_exchange.rb:18:in `request_rate'
     # ./spec/lib/money/bank/xe_exchange_spec.rb:11:in `block (4 levels) in <top (required)>'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:148:in `instance_exec'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:148:in `block in run'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `call'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `block (2 levels) in <class:Procsy>'
     # ./spec/spec_helper.rb:112:in `block (2 levels) in <top (required)>'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:294:in `instance_exec'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:294:in `instance_exec'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:430:in `block (2 levels) in run'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `call'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `block (2 levels) in <class:Procsy>'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:428:in `run'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:485:in `run'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:303:in `with_around_example_hooks'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:145:in `run'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:494:in `block in run_examples'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:490:in `map'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:490:in `run_examples'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:457:in `run'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:458:in `block in run'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:458:in `map'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:458:in `run'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:458:in `block in run'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:458:in `map'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:458:in `run'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:112:in `block (2 levels) in run_specs'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:112:in `map'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:112:in `block in run_specs'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/reporter.rb:54:in `report'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:108:in `run_specs'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:86:in `run'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:70:in `run'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:38:in `invoke'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/gems/rspec-core-3.0.4/exe/rspec:4:in `<top (required)>'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/bin/rspec:23:in `load'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/bin/rspec:23:in `<main>'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `eval'
     # /home/argon/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `<main>'

```

Our guess is that fakefs proceed to work even outside of the scope where it was initialized or may be there are some incompatibility between fakefs and openuri.

If you need any additional info please be sure to ask me.
Thank you!

**Comment by smtlaissezfaire** [comment]
Can you provide a unit test?  I'd be happy to take a patch request.

**Comment by HerbCSO** [comment]
See #290 for a test script. It's not a unit test, but a way to reproduce the issue.
