### ISSUE TITLE
open-uri open causes No such file or directory when FakeFS is activated

### ISSUE THREAD

**Issue by Alwahsh** [fakefs/fakefs#290]
Hello,

Everything used to work correctly, till I today tried to upgrade from rails 4.1.4 to rails 4.2.0. 
My tests started to fail saying that files don't exist. These files were links to websites. I tried to know the cause of the issue and finally I did the following in rails console and thus guessed that FakeFS is the reason.

``` ruby
2.1.0 :001 > link = open("https://google.com")
 => #<Tempfile:/tmp/open-uri20150227-25818-6qmb4h> 
2.1.0 :002 > require 'fakefs/spec_helpers'
 => true 
2.1.0 :003 > FakeFS.activate!
 => true 
2.1.0 :004 > link = open("https://google.com")
Errno::ENOENT: No such file or directory - https://google.com
        from /home/a/.rvm/gems/ruby-2.1.0/gems/fakefs-0.6.7/lib/fakefs/file.rb:599:in `check_file_existence!'
        from /home/a/.rvm/gems/ruby-2.1.0/gems/fakefs-0.6.7/lib/fakefs/file.rb:383:in `initialize'
        from /home/a/.rvm/gems/ruby-2.1.0/gems/fakefs-0.6.7/lib/fakefs/kernel.rb:39:in `open'
        from /home/a/.rvm/gems/ruby-2.1.0/gems/fakefs-0.6.7/lib/fakefs/kernel.rb:39:in `block in <module:Kernel>'
        from (irb):4
        from /home/a/.rvm/gems/ruby-2.1.0/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
        from /home/a/.rvm/gems/ruby-2.1.0/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
        from /home/a/.rvm/gems/ruby-2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /home/a/.rvm/gems/ruby-2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/a/.rvm/gems/ruby-2.1.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

I tried to go back to rails 4.1.4 but still the issue isn't resolved... It's as if that upgrade triggerred something that caused the problem.

**Comment by tylercollier** [comment]
Note that a naked `open` like that uses the Kernel class. Try `File.open`.

**Comment by HerbCSO** [comment]
This seems to have been broken in the 0.5.3 release somewhere. 

Test case:

* Create a `Gemfile` with:
```
source 'https://rubygems.org'

gem 'fakefs', '= 0.5.2'
```
* Run `bundle install`
* Create a file `test.rb` with:
```ruby
require 'fakefs/safe'
require 'open-uri'

FakeFS do; end

temp = open('/dev/null')
temp.close
temp = open('https://google.com/')
temp.close
```
* Run `bundle exec ./test.rb`, no errors
* Update `Gemfile` to use 0.5.3, run `bundle install` and `bundle exec ./test.rb` again, now you get the error:
```
/Users/carsten.dreesbach/.rvm/gems/ruby-2.2.0/gems/fakefs-0.5.3/lib/fakefs/kernel.rb:18:in `initialize': No such file or directory @ rb_sysopen - https://google.com/ (Errno::ENOENT)
        from /Users/carsten.dreesbach/.rvm/gems/ruby-2.2.0/gems/fakefs-0.5.3/lib/fakefs/kernel.rb:18:in `open'
        from /Users/carsten.dreesbach/.rvm/gems/ruby-2.2.0/gems/fakefs-0.5.3/lib/fakefs/kernel.rb:18:in `call'
        from /Users/carsten.dreesbach/.rvm/gems/ruby-2.2.0/gems/fakefs-0.5.3/lib/fakefs/kernel.rb:18:in `block (2 levels) in unhijack!'
        from ./test.rb:8:in `<main>'
```

I'm not sure yet what exactly broke OpenURI, but clearly this used to work prior to 0.5.3.

I also tested in Ruby 1.9.3, 2.0, 2.1 and 2.2, they all behave the same - 0.5.2 works, 0.5.3 breaks.

**Comment by Alwahsh** [comment]
The solution I chose eventually was to switch to curb instead of open-uri.

**Comment by HerbCSO** [comment]
curb may be the better option since open-uri monkey patches Kernel and open-uri has some serious [security concerns](http://sakurity.com/blog/2015/02/28/openuri.html).

That being said, I'd still love to see a fix for this.

**Comment by HerbCSO** [comment]
It looks like 76483b56086eb9df74d584425838e2a760a7afc7 introduced the issue.

**Comment by HerbCSO** [comment]
This appears to be fixed as of 0.7.0 - can probably be closed.

**Comment by grosser** [comment]
thx for confirming!

**Comment by paneq** [comment]
I am experiencing something similar

```
/Users/rupert/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/fakefs-1.3.2/lib/fakefs/file.rb:875:in `check_file_existence!': No such file or directory - /dev/null (Errno::ENOENT)
	from /Users/rupert/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/fakefs-1.3.2/lib/fakefs/file.rb:498:in `initialize'
	from /Users/rupert/.rbenv/versions/2.4.10/lib/ruby/2.4.0/rubygems/user_interaction.rb:684:in `open'
	from /Users/rupert/.rbenv/versions/2.4.10/lib/ruby/2.4.0/rubygems/user_interaction.rb:684:in `initialize'
	from /Users/rupert/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/ui/rg_proxy.rb:11:in `initialize'
	from /Users/rupert/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler.rb:74:in `new'
	from /Users/rupert/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler.rb:74:in `ui='
	from /Users/rupert/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/cli.rb:20:in `rescue in start'
	from /Users/rupert/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/cli.rb:24:in `start'
	from /Users/rupert/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
	from /Users/rupert/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	from /Users/rupert/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
	from /Users/rupert/.rbenv/versions/2.4.10/bin/bundle:23:in `load'
	from /Users/rupert/.rbenv/versions/2.4.10/bin/bundle:23:in `<main>'
```

**Comment by grosser** [comment]
PR welcome
