### ISSUE TITLE
Difference in raised errors

### ISSUE THREAD

**Issue by hardipe** [fakefs/fakefs#293]
There is an inconsistency in the raised error, making it difficult if not impossible to properly test exception handling:

```ruby
FakeFS { FileUtils.cp_r('/nonexistent', '/') } #RuntimeError: unknown file type: /nonexistent
FileUtils.cp_r('/nonexistent', '/') #Errno::ENOENT: No such file or directory - /nonexistent

#whereas
FakeFS { FileUtils.cp('/nonexistent', '/') } #Errno::ENOENT: No such file or directory - /nonexistent
FileUtils.cp('/nonexistent', '/') #Errno::ENOENT: No such file or directory - /nonexistent
```

Using gem version 0.6.7

**Comment by sometimesfood** [comment]
The `RuntimeError` duplicates the behaviour of Ruby 1.8.7:

```
~ % ruby --version
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]
~ % ruby -rfileutils -e 'FileUtils.cp_r("/nonexistent", "/tmp")'
/usr/lib/ruby/1.8/fileutils.rb:1262:in `copy': unknown file type: /nonexistent (RuntimeError)
	from /usr/lib/ruby/1.8/fileutils.rb:452:in `copy_entry'
	from /usr/lib/ruby/1.8/fileutils.rb:1331:in `traverse'
	from /usr/lib/ruby/1.8/fileutils.rb:449:in `copy_entry'
	from /usr/lib/ruby/1.8/fileutils.rb:424:in `cp_r'
	from /usr/lib/ruby/1.8/fileutils.rb:1402:in `fu_each_src_dest'
	from /usr/lib/ruby/1.8/fileutils.rb:1416:in `fu_each_src_dest0'
	from /usr/lib/ruby/1.8/fileutils.rb:1400:in `fu_each_src_dest'
	from /usr/lib/ruby/1.8/fileutils.rb:423:in `cp_r'
	from -e:1
~ %
```

I'll submit a pull request to fix this.
