### ISSUE TITLE
Errno::ENOENT: No such file or directory when saving a file

### ISSUE THREAD

**Issue by fsproru** [fakefs/fakefs#318]
Hi there,

Thanks for fakefs. Such a useful gem. I'm using fakefs-0.6.7. I'm getting the Errno::ENOENT: No such file or directory error when saving a file. Here is some code that illustrates this problem:

``` ruby
...
FakeFS do
  File.open(path, File::WRONLY | File::CREAT) do |file|
    file.write(text)
  end
end
...
```

Any pointers ?

Thanks,
Alex

**Comment by eterry1388** [comment]
Have you tired creating the directory first?

```ruby
FileUtils.mkdir_p( path )
```

**Comment by gnikonorov** [comment]
@fsproru - I believe the issue you are describing is due to the fact that you do not create the directory portion of `path` before writing the file, as @eterry1388 suggests.

For example, I see that both `fakefs` and ruby proper raise `Errno::ENOENT` when trying to write in a sub-directory that does not exist:
```
 ~/projects/fakefs/.my_tests/test_issue_318 [master|…41]
21:58 $ cat writefile.rb
require 'fakefs'

path = 'subdir/file.txt'
text = 'foobar'
File.open(path, File::WRONLY | File::CREAT) do |file|
  file.write(text)
end
✔ ~/projects/fakefs/.my_tests/test_issue_318 [master|…41]
21:58 $ ruby writefile.rb
/home/gnikonorov/.gem/ruby/2.3.0/gems/fakefs-0.18.0/lib/fakefs/file.rb:807:in `create_missing_file': No such file or directory - subdir/file.txt (Errno::ENOENT)
	from /home/gnikonorov/.gem/ruby/2.3.0/gems/fakefs-0.18.0/lib/fakefs/file.rb:490:in `initialize'
	from writefile.rb:5:in `open'
	from writefile.rb:5:in `<main>'
✘-1 ~/projects/fakefs/.my_tests/test_issue_318 [master|…41]
21:58 $ vim writefile.rb
✔ ~/projects/fakefs/.my_tests/test_issue_318 [master|…41]
21:58 $ cat writefile.rb
#require 'fakefs'

path = 'subdir/file.txt'
text = 'foobar'
File.open(path, File::WRONLY | File::CREAT) do |file|
  file.write(text)
end
✔ ~/projects/fakefs/.my_tests/test_issue_318 [master|…41]
21:58 $ ruby writefile.rb
writefile.rb:5:in `initialize': No such file or directory @ rb_sysopen - subdir/file.txt (Errno::ENOENT)
	from writefile.rb:5:in `open'
	from writefile.rb:5:in `<main>'
✘-1 ~/projects/fakefs/.my_tests/test_issue_318 [master|…41]
21:58 $
```
However, when no sub-directory is provided, the behavior between `fakefs` and ruby proper is the same:
```
✔ ~/projects/fakefs/.my_tests/test_issue_318 [master|…41]
21:59 $ cat writefile.rb
#require 'fakefs'

path = 'file.txt'
text = 'foobar'
File.open(path, File::WRONLY | File::CREAT) do |file|
  file.write(text)
end
✔ ~/projects/fakefs/.my_tests/test_issue_318 [master|…41]
21:59 $ ruby writefile.rb
✔ ~/projects/fakefs/.my_tests/test_issue_318 [master|…42]
21:59 $ cat file.txt
foobar✔ ~/projects/fakefs/.my_tests/test_issue_318 [master|…42]
21:59 $ vim writefile.rb
✔ ~/projects/fakefs/.my_tests/test_issue_318 [master|…42]
21:59 $ cat writefile.rb
require 'fakefs'

path = 'file.txt'
text = 'foobar'
File.open(path, File::WRONLY | File::CREAT) do |file|
  file.write(text)
end
✔ ~/projects/fakefs/.my_tests/test_issue_318 [master|…42]
21:59 $ ruby writefile.rb
✔ ~/projects/fakefs/.my_tests/test_issue_318 [master|…42]
21:59 $
```

I also see that the error does not occur when writing into a sub-directory that does exist:
```
✔ ~/projects/fakefs/.my_tests/test_issue_318 [master|…41]
22:02 $ cat writefile.rb
require 'fakefs'

Dir.mkdir('a_dir')

path = 'a_dir/file.txt'
text = 'foobar'
File.open(path, File::WRONLY | File::CREAT) do |file|
  file.write(text)
end
✔ ~/projects/fakefs/.my_tests/test_issue_318 [master|…41]
22:02 $ ruby writefile.rb
✔ ~/projects/fakefs/.my_tests/test_issue_318 [master|…41]
22:02 $ vim writefile.rb
✔ ~/projects/fakefs/.my_tests/test_issue_318 [master|…41]
22:02 $ cat writefile.rb
#require 'fakefs'

Dir.mkdir('a_dir')

path = 'a_dir/file.txt'
text = 'foobar'
File.open(path, File::WRONLY | File::CREAT) do |file|
  file.write(text)
end
✔ ~/projects/fakefs/.my_tests/test_issue_318 [master|…41]
22:02 $ ruby writefile.rb
✔ ~/projects/fakefs/.my_tests/test_issue_318 [master|…42]
22:02 $
```

**Comment by gnikonorov** [comment]
I'm going to close this out since it's quite stale, but please @fsproru feel free to re-open this if I did not sufficiently answer your question.
