### ISSUE TITLE
"TypeError: can't convert Tempfile to IO (Tempfile#to_io gives FakeFS::File)"

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [fakefs/fakefs#340]
I have one test of code that outputs to stderr.

When I set an expectation ... 

> output(/hhh/).to_stderr   (or to_stderr_on_any_process)

I get this error when running it:

> "TypeError: can't convert Tempfile to IO (Tempfile#to_io gives FakeFS::File)"

If I change the expectation to be to_stdout then it runs (but test fails as code outputs to stderr).

if I change the code to output to stdout and the expectation to match, then all runs and passes....

But I'd like the code to output to stderr and have the test pass...

Any ideas on the cause of this problem?

I dug into the code and got lost quickly....

**Comment by grosser** [comment]
no idea ... got a backtrace ... or can you add a failing test case to fakefs ?

**Comment by andrewdavidmackenzie** [comment]
I'm doing a PR now, but it maybe something to do with what looks like stderr creating a tempory file in '/tmp' from this message:

Errno::ENOENT: No such file or directory - /tmp/stderr20160320--9vv9lq
./lib/fakefs/file.rb:649:in `create_missing_file'
./lib/fakefs/file.rb:405:in `initialize'
./lib/fakefs/dir.rb:188:in `create'
./spec/fakefs/failing_spec.rb:25:in `block (2 levels) in <top (required)>'
-e:1:in `load'
-e:1:in `<main>'

**Comment by andrewdavidmackenzie** [comment]
See PR with passing/failing rspec tests that illustrate the error, plus some test in the test that describes different versions of the failure as you modify things:

https://github.com/fakefs/fakefs/pull/341

**Comment by grosser** [comment]
The basic problem ... Tempfile#to_io normally creates a File opbject ... now creates a FakeFS::File ... and IO#reopen is being super specific about what exactly it wants :(

```Ruby
io = IO.new(1)
io.reopen(Tempfile.new('xxx'))
```

ideas:
 - overwrite reopen to somehow convert to a FakeFS::File into IO object or File
 - make FakeFS::File inherit from IO
 - make Tempfile#to_io return an IO / regular file instead of FakeFS::File

none of these sound very nice ... 
if we can somehow turn a FakeFS::File into something that inherits from IO we could return that from Tempfile#to_io ... but not sure how much work that is ...

please try to make a patch if possible ... otherwise you might be able to use `Dir.mktmpdir{|d| Dir.chdir(d){ runtests in here }}` to avoid the issue ...

**Comment by MichaelSp** [comment]
Here is another one:

```(ruby)
it "can diff" do
  FakeFS.with do
        assert_equal "a"*30, "b"*30
   end
end
```

This throws the following exception:
```
Minitest::UnexpectedError: Errno::ENOENT: No such file or directory - /tmp/expect20170125--y192yw
    /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fakefs-0.10.2/lib/fakefs/file.rb:654:in `create_missing_file'
    /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fakefs-0.10.2/lib/fakefs/file.rb:410:in `initialize'
    /Users/me/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tempfile.rb:133:in `open'
    /Users/me/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tempfile.rb:133:in `block in initialize'
    /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fakefs-0.10.2/lib/fakefs/dir.rb:189:in `create'
    /Users/me/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tempfile.rb:131:in `initialize'
    /Users/me/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tempfile.rb:291:in `new'
    /Users/me/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tempfile.rb:291:in `open'
/Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fakefs-0.10.2/lib/fakefs/file.rb:654:in `create_missing_file'
/Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fakefs-0.10.2/lib/fakefs/file.rb:410:in `initialize'
/Users/me/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tempfile.rb:133:in `open'
/Users/me/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tempfile.rb:133:in `block in initialize'
/Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fakefs-0.10.2/lib/fakefs/dir.rb:189:in `create'
/Users/me/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tempfile.rb:131:in `initialize'
/Users/me/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tempfile.rb:291:in `new'
/Users/me/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tempfile.rb:291:in `open'
```

This is what happens:
https://github.com/seattlerb/minitest/blob/master/lib/minitest/assertions.rb#L75-L97

I'd expect this test to fail with
```
Minitest::Assertion: Expected: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  Actual: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
```

**Comment by brandonweiss** [comment]
I think I have the same problem… I have a test that I want to use `{ }.must_output` in order to assert that certain output is returned. If I just call the method I'm testing everything is fine. But if I wrap it in a `must_output` block then I get:

```
Errno::ENOENT: No such file or directory - /tmp/expect20170725--1f232va
    /Users/brandon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fakefs-0.11.0/lib/fakefs/file.rb:654:in `create_missing_file'
    /Users/brandon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fakefs-0.11.0/lib/fakefs/file.rb:410:in `initialize'
    /Users/brandon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tempfile.rb:133:in `open'
    /Users/brandon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tempfile.rb:133:in `block in initialize'
    /Users/brandon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fakefs-0.11.0/lib/fakefs/dir.rb:189:in `create'
    /Users/brandon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tempfile.rb:131:in `initialize'
    /Users/brandon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tempfile.rb:291:in `new'
    /Users/brandon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tempfile.rb:291:in `open'
```

**Comment by RedFred7** [comment]
any news on this one guys?
