### ISSUE TITLE
Usability issue: block call does not reset state

### ISSUE THREAD

**Issue by cburgmer** [fakefs/fakefs#343]
We are using FakeFS in the fashion as described in the README:
```
FakeFS do
  # your code
end
```
We noticed that for two independent tests the one run last would start failing, because a certain directory already existed. We solved that by calling `FakeFS::FileSystem.clear`.

The expectation was that the blocked call would behave similar to e.g. `TimeCop.freeze {}` where no state is maintained.

Preferred behaviour would be to start from a clean state. Alternatively I would be helpful to call out this behaviour in the README.

**Comment by grosser** [comment]
from the readme it looks like the block is supposed to be like an active/deactivate ... so maybe a clear option or at least PR to document this possibly unexected behavior ...

**Comment by brandonweiss** [comment]
Yeah, this is odd. I actually see the same thing with `activate!` and `deactivate!`. I'm calling activate before each test and deactivate afterwards, but state seems to be leaking between tests.

**Comment by grosser** [comment]
even worse ... can you open the gem and poke around to find the root cause ?

**Comment by brandonweiss** [comment]
I can try… just to be clear, this is what I'm doing:

```ruby
require "fakefs/safe"
require "minitest/autorun"

describe "test" do

  before do
    FakeFS.activate!
  end

  after do
    FakeFS.deactivate!
  end

  it "creates a file" do
    Dir.mkdir("./test")
  end

  it "creates a file again" do
    Dir.mkdir("./test")
  end

end
```

And it fails with:

```
Errno::EEXIST: File exists - ./test
    /Users/brandon/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fakefs-0.10.0/lib/fakefs/fileutils.rb:42:in `block in mkdir'
    /Users/brandon/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fakefs-0.10.0/lib/fakefs/fileutils.rb:36:in `each'
    /Users/brandon/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fakefs-0.10.0/lib/fakefs/fileutils.rb:36:in `mkdir'
    /Users/brandon/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fakefs-0.10.0/lib/fakefs/dir.rb:125:in `mkdir'
    fakefs.rb:19:in `block (2 levels) in <main>'
```

I just want to make sure that that is actually unexpected, because this is a pretty big bug, isn't it? And it's been happening since June 2nd? Is this only happening to a few people or is it happening for everyone?

**Comment by grosser** [comment]
might be a 'feature' ... got to find where it is happening and then git
blame to see how long it was there ...

**Comment by Epigene** [comment]
I see it as a feature, allowing the fake file system to retain data across examples. This is useful for shared setup in those `before :all` blocks.

A quick glance at the code reveals `FakeFS::FileSystem.clear` as a possible workaround if you need the filesystem to be pristine in each run.

**Comment by brandonweiss** [comment]
I don't think it's a “feature”… If you deactivate, and then re-activate, there's no reason why the state should be maintained… if that's what you wanted then you just wouldn't deactivate to begin with. I believe the proper way to maintain the fake filesystem across all tests is to activate it and then just never deactivate it. If you deactivate it or use the block syntax, I'm pretty sure the intention is that the state should be cleared.

**Comment by grosser** [comment]
Yeah sounds weird/unexpected to me too ... we got with_fresh for that now
... so breaking less existing code ...
A PR to make fresh the default and add with_persistent would be nice though
...
