### ISSUE TITLE
FileUtils.move doesn't move file

### ISSUE THREAD

**Issue by tobymurray-nanometrics** [fakefs/fakefs#346]
It's very possible I've botched something trivial up, but is this as expected?

In `spec_helper.rb`
```
require 'fakefs/spec_helpers'
RSpec.configure do |config|
  config.include FakeFS::SpecHelpers, fakefs: true
end
```

```
describe "file manipulation", fakefs: true do
  it "should work" do
    ORIGINAL_DIRECTORY = "original_directory"
    OTHER_DIRECTORY = "other_directory"
    FileUtils.mkdir(ORIGINAL_DIRECTORY)
    FileUtils.mkdir(OTHER_DIRECTORY)

    FileUtils.touch(File.join(ORIGINAL_DIRECTORY, "test_file"))
    file = File.new(File.join(ORIGINAL_DIRECTORY, "test_file"))

    FileUtils.move(file, OTHER_DIRECTORY)

    Rails.logger.debug(file.inspect)
    // #<FakeFS::File:0x337fd6a1 @file=(FakeFile name:"test_file" parent:"/original_directory" size:0), @mode="r", @path="original_directory/test_file", @autoclose=true>
  end
end
```
## Expected
`file.parent == OTHER_DIRECTORY`

## Actual
`file.parent == ORIGINAL_DIRECTORY`

## Environment:
Windows 10
Rails 4.2.6
RSpec 3.5.0
jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f Java HotSpot(TM) 64-Bit Server VM 25.92-b14 on 1.8.0_92-b14 +jit [mswin32-x86_64]

**Comment by grosser** [comment]
does it work when not using fakefs ?

**Comment by tobymurray-nanometrics** [comment]
@grosser - no. That's a little bit embarrassing. It doesn't work without fakefs, I must have implemented it differently in the past. Sorry!

(tried in both JRuby 9.1.2.0 and 1.7.25, example below). 
```
λ jirb                                                                                   
irb(main):001:0>                                                                         
irb(main):002:0* require 'fileutils'                                                     
=> true                                                                                  
irb(main):003:0> FileUtils.mkdir("first_directory")                                      
=> ["first_directory"]                                                                   
irb(main):004:0> FileUtils.mkdir("second_directory")                                     
=> ["second_directory"]                                                                  
irb(main):005:0> FileUtils.touch(File.join("first_directory", "test_file"))              
=> ["first_directory/test_file"]                                                         
irb(main):006:0> file = File.new(File.join("first_directory", "test_file"))              
=> #<File:first_directory/test_file>                                                     
irb(main):007:0> FileUtils.move(file, "second_directory")                                
Errno::EACCES: Permission denied - first_directory/test_file                             
        from org/jruby/RubyFile.java:1129:in `unlink'                                    
        from C:/jruby/jruby-1.7.25/lib/ruby/1.9/fileutils.rb:1416:in `remove_file'       
        from C:/jruby/jruby-1.7.25/lib/ruby/1.9/fileutils.rb:1421:in `platform_support'  
        from C:/jruby/jruby-1.7.25/lib/ruby/1.9/fileutils.rb:1415:in `remove_file'       
        from C:/jruby/jruby-1.7.25/lib/ruby/1.9/fileutils.rb:1404:in `remove'            
        from C:/jruby/jruby-1.7.25/lib/ruby/1.9/fileutils.rb:780:in `remove_entry'       
        from C:/jruby/jruby-1.7.25/lib/ruby/1.9/fileutils.rb:1458:in `postorder_traverse'
        from C:/jruby/jruby-1.7.25/lib/ruby/1.9/fileutils.rb:778:in `remove_entry'       
        from C:/jruby/jruby-1.7.25/lib/ruby/1.9/fileutils.rb:525:in `mv'                 
        from C:/jruby/jruby-1.7.25/lib/ruby/1.9/fileutils.rb:1525:in `fu_each_src_dest'  
        from C:/jruby/jruby-1.7.25/lib/ruby/1.9/fileutils.rb:1539:in `fu_each_src_dest0' 
        from C:/jruby/jruby-1.7.25/lib/ruby/1.9/fileutils.rb:1523:in `fu_each_src_dest'  
        from C:/jruby/jruby-1.7.25/lib/ruby/1.9/fileutils.rb:508:in `mv'                 
        from (irb):7:in `evaluate'                                                       
        from org/jruby/RubyKernel.java:1079:in `eval'                                    
        from org/jruby/RubyKernel.java:1479:in `loop'                                    
        from org/jruby/RubyKernel.java:1242:in `catch'                                   
        from org/jruby/RubyKernel.java:1242:in `catch'                                   
        from C:/jruby/jruby-1.7.25/bin/jirb:13:in `(root)'irb(main):008:0>               
```

**Comment by tobymurray-nanometrics** [comment]
On the off chance anyone else runs into this, my issue was the `file = File.new(File.join("first_directory", "test_file"))` line. I was assuming I was just getting a file pointer, but it actually opens the file. Files that are actively in use can't be moved, so the operation was failing. Removing this line and referring to the file by path only works as expected.
