### ISSUE TITLE
Undefined method Pathname#write

### ISSUE THREAD

**Issue by alem0lars** [fakefs/fakefs#381]
Pathname inherits some FileUtils and File methods, like `#write`.

However in the fake version the method isn't available.

**Comment by grosser** [comment]
Pr welcome!

**Comment by malakai97** [comment]
Should be able to use #387 as a model

**Comment by gnikonorov** [comment]
Noting that this is still partially broken:

Without `fakefs`:
```
~/projects/fakefs/.my_tests/test_issue_381 [master|…47]
15:47 $ cat pathname_write.rb
require 'pathname'

file = Pathname('test_file')
file.write 'called pathname.write'
~/projects/fakefs/.my_tests/test_issue_381 [master|…47]
15:47 $ ruby pathname_write.rb
~/projects/fakefs/.my_tests/test_issue_381 [master|…48]
15:47 $ cat test_file
called pathname.write
```

With `fakefs`:
```
~/projects/fakefs/.my_tests/test_issue_381 [master|…48]
15:47 $ cat pathname_write.rb
require 'pathname'
require 'fakefs'

file = Pathname('test_file')
file.write 'called pathname.write'
~/projects/fakefs/.my_tests/test_issue_381 [master|…48]
15:47 $ ruby pathname_write.rb
/home/gnikonorov/.gem/ruby/2.3.0/gems/fakefs-0.18.0/lib/fakefs/pathname.rb:790:in `write': wrong number of arguments (given 1, expected 2) (ArgumentError)
	from pathname_write.rb:5:in `<main>'
~/projects/fakefs/.my_tests/test_issue_381 [master|…48]
15:47 $
```

**Comment by skalee** [comment]
Also `Pathname#binwrite` is missing, which has been added in Ruby 2.1 ([changelog](https://github.com/ruby/ruby/blob/v2_1_0/NEWS)).

**Comment by skalee** [comment]
It seems not that trivial as I thought initially. :)

For instance, it puzzles me why fake `Pathname#write` opens file in a binary mode.

**Comment by grosser** [comment]
maybe start with the tests of how it should behave and then others can help
if there are issues

**Comment by iainbryson** [comment]
I've creates a PR which I think addresses this.  It makes no sense to path the path as an argument to `pathname#write`. It at least addresses my problem, which was webpacker failing when using FakeFS:

```
    ActionView::Template::Error:
       wrong number of arguments (given 1, expected 2)
     # /Users/iain/.rvm/gems/ruby-2.5.1/gems/fakefs-0.20.0/lib/fakefs/pathname.rb:790:in `write'
     # /Users/iain/.rvm/gems/ruby-2.5.1/gems/webpacker-4.0.2/lib/webpacker/compiler.rb:55:in `record_compilation_digest'
     # /Users/iain/.rvm/gems/ruby-2.5.1/gems/webpacker-4.0.2/lib/webpacker/compiler.rb:22:in `block in compile'
     # /Users/iain/.rvm/gems/ruby-2.5.1/gems/webpacker-4.0.2/lib/webpacker/compiler.rb:21:in `tap'
     # /Users/iain/.rvm/gems/ruby-2.5.1/gems/webpacker-4.0.2/lib/webpacker/compiler.rb:21:in `compile'
     # /Users/iain/.rvm/gems/ruby-2.5.1/gems/webpacker-4.0.2/lib/webpacker/manifest.rb:58:in `block in compile'
     # /Users/iain/.rvm/gems/ruby-2.5.1/gems/webpacker-4.0.2/lib/webpacker/manifest.rb:58:in `compile'
     # /Users/iain/.rvm/gems/ruby-2.5.1/gems/webpacker-4.0.2/lib/webpacker/manifest.rb:42:in `lookup'
     # /Users/iain/.rvm/gems/ruby-2.5.1/gems/webpacker-4.0.2/lib/webpacker/manifest.rb:49:in `lookup!'
     # /Users/iain/.rvm/gems/ruby-2.5.1/gems/webpacker-4.0.2/lib/webpacker/helper.rb:137:in `block in sources_from_manifest_entries'
     # /Users/iain/.rvm/gems/ruby-2.5.1/gems/webpacker-4.0.2/lib/webpacker/helper.rb:137:in `map'
     # /Users/iain/.rvm/gems/ruby-2.5.1/gems/webpacker-4.0.2/lib/webpacker/helper.rb:137:in `sources_from_manifest_entries'
     # /Users/iain/.rvm/gems/ruby-2.5.1/gems/webpacker-4.0.2/lib/webpacker/helper.rb:105:in `stylesheet_pack_tag'
     # ./app/views/layouts/md_rendered_page.html.erb:6:in `_app_views_layouts_md_rendered_page_html_erb__4464295593350511275_70242162206640'
     # ./app/helpers/home_helper.rb:9:in `render_page'
     # ./app/controllers/md_single_page_controller.rb:191:in `show_view'
     # ./app/controllers/md_single_page_controller.rb:161:in `show_static'
     # ./app/controllers/md_single_page_controller.rb:46:in `show'
     # /Users/iain/.rvm/gems/ruby-2.5.1/gems/rails-controller-testing-1.0.4/lib/rails/controller/testing/template_assertions.rb:61:in `process'
     # /Users/iain/.rvm/gems/ruby-2.5.1/gems/rails-controller-testing-1.0.4/lib/rails/controller/testing/integration.rb:13:in `block (2 levels) in <module:Integration>'
     # ./spec/controllers/md_single_page_controller_spec.rb:33:in `block (4 levels) in <top (required)>'
     # /Users/iain/.rvm/gems/ruby-2.5.1/gems/fakefs-0.20.0/lib/fakefs/base.rb:84:in `with'
     # /Users/iain/.rvm/gems/ruby-2.5.1/gems/fakefs-0.20.0/lib/fakefs/base.rb:109:in `FakeFS'
     # ./spec/controllers/md_single_page_controller_spec.rb:23:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # ArgumentError:
     #   wrong number of arguments (given 1, expected 2)
     #   /Users/iain/.rvm/gems/ruby-2.5.1/gems/fakefs-0.20.0/lib/fakefs/pathname.rb:790:in `write'
```
