### ISSUE TITLE
Can't chmod in symbolic mode.

### ISSUE THREAD

**Issue by gnikonorov** [fakefs/fakefs#417]
Ruby allows for us to pass `chmod` arguments in [symbolic node](https://ruby-doc.org/stdlib-1.9.3/libdoc/fileutils/rdoc/FileUtils.html#method-c-chmod). `fakefs`, however, will error when we try to do this.

For example, with `fakefs`:
```
✔ ~/projects/fakefs/.my_tests/test_chmod_for_non_octal_numbers [master|…33]
19:06 $ lls
total 4
-rw-rw-r-- 1 gnikonorov gnikonorov 705 Jul 17 19:04 chmod_a_lot.rb
✔ ~/projects/fakefs/.my_tests/test_chmod_for_non_octal_numbers [master|…33]
19:06 $ cat chmod_a_lot.rb
require 'fileutils'
require 'fakefs'

file_name = 'test_file.txt'

FileUtils.touch file_name
curr_umask = File.stat(file_name).mode.to_s(8)
puts "Curr file umask is #{curr_umask.to_s}"

FileUtils.chmod("ugo=wrx", file_name)
curr_umask = File.stat(file_name).mode.to_s(8)
puts "Curr file umask is #{curr_umask.to_s}"

FileUtils.chmod("ugo=wr", file_name)
curr_umask = File.stat(file_name).mode.to_s(8)
puts "Curr file umask is #{curr_umask.to_s}"

FileUtils.chmod("ugo=r", file_name)
curr_umask = File.stat(file_name).mode.to_s(8)
puts "curr file umask is #{curr_umask.to_s}"

FileUtils.chmod("ugo=rx", file_name)
curr_umask = File.stat(file_name).mode.to_s(8)
puts "Curr file umask is #{curr_umask.to_s}"
✔ ~/projects/fakefs/.my_tests/test_chmod_for_non_octal_numbers [master|…33]
19:06 $ ruby chmod_a_lot.rb
Curr file umask is 100664
/home/gnikonorov/.gem/ruby/2.3.0/gems/fakefs-0.16.0/lib/fakefs/file.rb:285:in `+': String can't be coerced into Fixnum (TypeError)
	from /home/gnikonorov/.gem/ruby/2.3.0/gems/fakefs-0.16.0/lib/fakefs/file.rb:285:in `chmod'
	from /home/gnikonorov/.gem/ruby/2.3.0/gems/fakefs-0.16.0/lib/fakefs/fileutils.rb:244:in `block in chmod'
	from /home/gnikonorov/.gem/ruby/2.3.0/gems/fakefs-0.16.0/lib/fakefs/fileutils.rb:242:in `each'
	from /home/gnikonorov/.gem/ruby/2.3.0/gems/fakefs-0.16.0/lib/fakefs/fileutils.rb:242:in `chmod'
	from chmod_a_lot.rb:10:in `<main>'
✘-1 ~/projects/fakefs/.my_tests/test_chmod_for_non_octal_numbers [master|…33]
19:06 $
```

while without it:
```
✔ ~/projects/fakefs/.my_tests/test_chmod_for_non_octal_numbers [master|…33]
19:06 $ lls
total 4
-rw-rw-r-- 1 gnikonorov gnikonorov 706 Jul 17 19:06 chmod_a_lot.rb
✔ ~/projects/fakefs/.my_tests/test_chmod_for_non_octal_numbers [master|…33]
19:06 $ cat chmod_a_lot.rb
require 'fileutils'
#require 'fakefs'

file_name = 'test_file.txt'

FileUtils.touch file_name
curr_umask = File.stat(file_name).mode.to_s(8)
puts "Curr file umask is #{curr_umask.to_s}"

FileUtils.chmod("ugo=wrx", file_name)
curr_umask = File.stat(file_name).mode.to_s(8)
puts "Curr file umask is #{curr_umask.to_s}"

FileUtils.chmod("ugo=wr", file_name)
curr_umask = File.stat(file_name).mode.to_s(8)
puts "Curr file umask is #{curr_umask.to_s}"

FileUtils.chmod("ugo=r", file_name)
curr_umask = File.stat(file_name).mode.to_s(8)
puts "curr file umask is #{curr_umask.to_s}"

FileUtils.chmod("ugo=rx", file_name)
curr_umask = File.stat(file_name).mode.to_s(8)
puts "Curr file umask is #{curr_umask.to_s}"
✔ ~/projects/fakefs/.my_tests/test_chmod_for_non_octal_numbers [master|…33]
19:06 $ ruby chmod_a_lot.rb
Curr file umask is 100664
Curr file umask is 100777
Curr file umask is 100666
curr file umask is 100444
Curr file umask is 100555
✔ ~/projects/fakefs/.my_tests/test_chmod_for_non_octal_numbers [master|…34]
19:06 $ lls
total 4
-rw-rw-r-- 1 gnikonorov gnikonorov 706 Jul 17 19:06 chmod_a_lot.rb
-r-xr-xr-x 1 gnikonorov gnikonorov   0 Jul 17 19:06 test_file.txt
✔ ~/projects/fakefs/.my_tests/test_chmod_for_non_octal_numbers [master|…34]
19:06 $
```

I will add in support for `symbolic mode` and chmodding.

**Comment by gnikonorov** [comment]
Noting I'll DRY up the prior pull request as part of part two of this fix as suggested here: https://github.com/fakefs/fakefs/pull/418.

**Comment by gnikonorov** [comment]
Working on adding support for `+/-` and should have a pull request up tomorrow evening.
