### ISSUE TITLE
FakeFS::File#lock raises NotImplementedError

### ISSUE THREAD

**Issue by etagwerker** [fakefs/fakefs#433]
Hi there, 

I'm trying to add a feature (more here: https://github.com/whitesmith/rubycritic/pull/319)  to `rubycritic` which depends on `fakefs` and I'm getting this exception:

```
2) Error:
RubyCritic::Generator::LintReport::#generate_report#test_0001_report file has data inside:
NotImplementedError: NotImplementedError
  /Users/etagwerker/.rvm/gems/ruby-2.6.2@rubycritic/gems/fakefs-0.20.1/lib/fakefs/file.rb:577:in `flock'
  /home/rubycritic/lib/rubycritic/analysers/coverage.rb:91:in `block in synchronize_resultset'
  /home/rubycritic/lib/rubycritic/analysers/coverage.rb:90:in `open'
  /home/rubycritic/lib/rubycritic/analysers/coverage.rb:90:in `synchronize_resultset'
  /home/rubycritic/lib/rubycritic/analysers/coverage.rb:74:in `stored_data'
  /home/rubycritic/lib/rubycritic/analysers/coverage.rb:59:in `resultset'
  /home/rubycritic/lib/rubycritic/analysers/coverage.rb:105:in `results'
  /home/rubycritic/lib/rubycritic/analysers/coverage.rb:15:in `initialize'
  /home/rubycritic/lib/rubycritic/analysers_runner.rb:30:in `new'
  /home/rubycritic/lib/rubycritic/analysers_runner.rb:30:in `block in run'
  /home/rubycritic/lib/rubycritic/analysers_runner.rb:29:in `each'
  /home/rubycritic/lib/rubycritic/analysers_runner.rb:29:in `run'
  /home/rubycritic/test/lib/rubycritic/generators/lint_report_test.rb:30:in `create_analysed_modules_collection'
  /home/rubycritic/test/lib/rubycritic/generators/lint_report_test.rb:18:in `block (3 levels) in <top (required)>'
```

I see that `flock` is not implemented in `fakefs`. If one were to try and implement it, what would that look like? 

For now I've solved it by doing this monkeypatch in my project:

```
module FakeFS
  class File < StringIO
    def flock(*)
      true
    end
  end
end
```

I know it is quite hacky and it could have some side effects. 

Any thoughts on how `flock` could be implemented in `fakefs`?

Thanks!

**Comment by grosser** [comment]
could use a hash of mutexes under the hood to make it kinda work
