### ISSUE TITLE
Calling FileUtils.touch on a symlink with a missing target throws an exception instead of creating the file

### ISSUE THREAD

**Issue by monfresh** [fakefs/fakefs#493]
Outside of FakeFS, if you use Ruby's normal FileUtils.touch, it will automatically create the file if it doesn't exist, even if it's a symlink to a nonexistent target. For example:

Create a file `~/.zshrc-original`
Symlink this file into ~/.zshrc: `ln -s ~/.zshrc-original ~/.zshrc`
Now remove the original file: `rm ~/.zshrc-original`
If you call `FileUtils.touch(File.expand_path("~/.zshrc"))`, it will automatically create an empty `~/.zshrc-original`.

However, when testing this in an RSpec test using FakeFS, where the symlink and original file and created, and the original file removed within FakeFS, and if the code under test calls `FileUtils.touch`, FakeFS crashes due to this error:

```
NoMethodError:
       undefined method `mtime=' for nil:NilClass

             entry.send(*args, &block)
                  ^^^^^
     # /Users/moncef/.gem/ruby/3.1.3/gems/fakefs-2.5.0/lib/fakefs/fake/symlink.rb:33:in `method_missing'
     # /Users/moncef/.gem/ruby/3.1.3/gems/fakefs-2.5.0/lib/fakefs/fileutils.rb:271:in `block in touch'
     # /Users/moncef/.gem/ruby/3.1.3/gems/fakefs-2.5.0/lib/fakefs/fileutils.rb:266:in `each'
     # /Users/moncef/.gem/ruby/3.1.3/gems/fakefs-2.5.0/lib/fakefs/fileutils.rb:266:in `touch'
```

I'm happy to submit a PR to fix this, but I'm not sure what the best approach is.

**Comment by grosser** [comment]
Sounds like a bug, pr welcome
