### ISSUE TITLE
Usability: Error on exit from IRB and history not saved if deactivate isn't called

### ISSUE THREAD

**Issue by uvlad7** [fakefs/fakefs#504]
```
/home/vladimir/.local/share/rtx/installs/ruby/2.3.8/lib/ruby/gems/2.3.0/gems/fakefs-1.2.1/lib/fakefs/file.rb:903:in `create_missing_file': No such file or directory - /home/vladimir/.irb_history (Errno::ENOENT)
	from /home/vladimir/.local/share/rtx/installs/ruby/2.3.8/lib/ruby/gems/2.3.0/gems/fakefs-1.2.1/lib/fakefs/file.rb:496:in `initialize'
	from /home/vladimir/.local/share/rtx/installs/ruby/2.3.8/lib/ruby/gems/2.3.0/gems/fakefs-1.2.1/lib/fakefs/kernel.rb:40:in `open'
	from /home/vladimir/.local/share/rtx/installs/ruby/2.3.8/lib/ruby/gems/2.3.0/gems/fakefs-1.2.1/lib/fakefs/kernel.rb:40:in `block in <module:Kernel>'
	from /home/vladimir/.local/share/rtx/installs/ruby/2.3.8/lib/ruby/2.3.0/irb/ext/save-history.rb:98:in `save_history'
	from /home/vladimir/.local/share/rtx/installs/ruby/2.3.8/lib/ruby/2.3.0/irb/ext/save-history.rb:64:in `block in extended'
	from /home/vladimir/.local/share/rtx/installs/ruby/2.3.8/lib/ruby/2.3.0/irb.rb:404:in `block in irb_at_exit'
	from /home/vladimir/.local/share/rtx/installs/ruby/2.3.8/lib/ruby/2.3.0/irb.rb:404:in `each'
	from /home/vladimir/.local/share/rtx/installs/ruby/2.3.8/lib/ruby/2.3.0/irb.rb:404:in `irb_at_exit'
	from /home/vladimir/.local/share/rtx/installs/ruby/2.3.8/lib/ruby/2.3.0/irb.rb:398:in `start'
	from /home/vladimir/.local/share/mise/installs/ruby/2.3.8/bin/irb:11:in `<main>'
```

**Comment by grosser** [comment]
would an at_exit block help with this ?

**Comment by uvlad7** [comment]
most likely yes, just needs to be registered after the one from IRB, which is not an issue in regular usage, unless IRB is stated somehow programmatically after fakefs is activated
